config/routes.rb
Blocmetrics::Application.routes.draw do
  
  
  namespace :api do
    namespace :v1 do
      resources :events
    end
  end
  
  root to: 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :site
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :set_headers
  respond_to :json

  def create
    @event = Event.new(event_params)
    
    @event.ip_address = request.remote_ip

    #append on the event information from  the request
    @event.name = request.referer

    if @event.save
      # give a success message, respond with the event created
      flash[:notice] = 'Event was successfully saved.'
      # respond_with
      respond_with @event.as_json, location: nil
    else
      # give an error message on why save failed
      flash[:notice] = 'Error has occured.'
      # @event.errors
      respond_with @event.errors
      # render :json
    end      
  end

  def update
    @event.update(event_params)

    if @event.save
      flash[:notice] = 'Event was updated.'
      respond_with @event
    else
      flash[:notice] = 'Event was no updated.'
      respond_with @event.errors
    end
  end

  def destroy
    @event.destroy
    respond_with @event
  end

  private

  def event_params
    params.require(:event).permit(:name, :ip_address, :eventtime)
  end

  def error(status, message = 'Error has occured')
    response = { response_type: "Error", message: message }
    render json: response.to_json, status: status
  end

  def permission_denied_error
    error(403, 'Permission Denied!')
  end

  def set_headers
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
      headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match'
      headers['Access-Control-Max-Age'] = '1728000'
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_Session, :if => Proc.new { |p1| p1.request.format == 'application/json'}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
  end

  #def create
   # @event = Event.new(params.require(:event).permit(:name, :ip_address, :eventtime))
   # @event.save
  #end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.textfield :name %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.textfield :ip_address %>
  </div>
  <div class="field">
    <%= f.label :eventtime %><br>
    <%= f.datetime :eventtime %>
  </div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">
  
    <h1>Event Sources</h1>
    
  <% for event in @events  %>
  
  <t body>
    <tr>
      
      <td><%=h event.name %></td>
      <td><%=h event.ip_address %></td>
      <td><%= event.created_at.to_s(:short) %></td>
      
    </tr>
  </t body>

  <% end %>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.eventtime %></td>
          <td><%= event.ip_address %></td>

        </tr>
      <% end %>
    </tbody>

    <%= @events.group(:name).count %>
     <!-- Data for line graph data showing all events by day --> 
     
  <div id="value-data" class="hidden">
    <%= @events.count(group: "DATE(created_at)").values %>
  </div>
  


  </div>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>ip_address:</strong>
  <%= @event.ip_address %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.eventtime %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <li><%= link_to "Blocmetrics", root_path %></li>
  

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmetrics</h1>
<p>The latest in Analytics</p>